reemplazar gtm tags en duro por lib: react-gtm-module
Asepy/fishswarm-frontend pull request #71
Opened 2022-01-20 17:37 UTC by manchavz

Debido a problemas de conexion cuando se ejecuta el debugger desde la pantalla web de Google Tag Manager sobre el enlace de la aplicacion web en el ambiente de desarrollo, opte por cambiar la integracion del mismo servicio con la Web-App.

Ahora se usa la libreria de npm "react-gtm-module"  en vez de escribir el codigo en duro del GTM tag en algun archivo que tenga presencia en todas las paginas de la web-app.

2022-01-20 20:19 UTC, rodrigojv requested changes
Hola @manchavz , te dejo unos comentarios. No se si llegaste a probar en tu local pero así como usaste el useEffect te podría haber intentado de inicializar más de una vez, pudiendo provocar algún error.

2022-01-20 20:19 UTC, rodrigojv commented on pages/_app.js
> +import { React, useEffect } from "react";
```suggestion
import React, { useEffect } from "react";
```

2022-01-20 20:19 UTC, rodrigojv commented on pages/_app.js
> +  });
```suggestion
  }, []);
```

2022-01-21 00:38 UTC, manchavz commented on pages/_app.js
> +  });
Buenas Rodri! Gracias por tus comentarios y feedback, los aprecio mucho. 

La verdad que cuando lo probe de manera local en mi maquina, no tuve errores de intentos de iniciar multiples veces el contenido del useEffect hook. 

Posiblemente haya tenido suerte en no ser afectado en este caso, pero gracias por resaltarlo. Me voy a informar mejor acerca de este punto y modificar el codigo segun tu sugerencia 😃

2022-01-21 00:41 UTC, manchavz commented on pages/_app.js
> +import { React, useEffect } from "react";
Voy a indagar acerca de esta sugerencia antes de preguntartelo, ya que lo veo como un concepto basico que deberia manejar de mi parte.

2022-01-30 15:04 UTC, rodrigojv commented
Hola @manchavz , esto ya está para mezclarse. Sólo deberíamos resolver los conflictos en package-lock.json.

2022-03-28 01:29 UTC, merged